# Generated by Django 4.2.9 on 2024-01-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieInfo",
            fields=[
                ("movie_id", models.AutoField(primary_key=True, serialize=False)),
                ("original_title", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("post", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("summary", models.TextField()),
                ("release_date", models.DateField()),
                ("reg_date", models.DateField()),
            ],
            options={
                "verbose_name": "영화정보",
                "verbose_name_plural": "영화정보",
                "db_table": "movie_info",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("nick_name", models.CharField(max_length=200)),
                ("reg_date", models.DateField()),
            ],
            options={
                "verbose_name": "사용자정보",
                "verbose_name_plural": "사용자정보",
                "db_table": "user_info",
            },
        ),
    ]
