# Generated by Django 4.2.9 on 2024-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobbie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="nick_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="reg_date",
            field=models.DateField(default=""),
        ),
    ]
