# Generated by Django 4.2.9 on 2024-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobbie", "0002_alter_userinfo_email_alter_userinfo_nick_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieinfo",
            name="grade",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="genre",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="original_title",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="post",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="reg_date",
            field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="release_date",
            field=models.DateField(default=""),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="summary",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="title",
            field=models.CharField(default="", max_length=500),
        ),
    ]
