# Generated by Django 4.2.9 on 2024-01-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobbie", "0004_movieinfo_surver_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieinfo",
            name="grade",
            field=models.FloatField(default=0),
        ),
    ]
