# Generated by Django 4.2.9 on 2024-01-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobbie", "0005_alter_movieinfo_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gengre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_id", models.IntegerField(default="")),
                ("genre_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "genre_info",
            },
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="reg_date",
            field=models.DateField(blank=True, default="1111-11-11", null=True),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="release_date",
            field=models.DateField(blank=True, default="1111-11-11", null=True),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="surver_id",
            field=models.TextField(blank=True, default="-", null=True),
        ),
    ]
