# Generated by Django 4.2.9 on 2024-01-27 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mobbie", "0007_alter_movieinfo_reg_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="", max_length=500)),
                ("content", models.TextField(default="")),
                ("grade", models.FloatField(default=0)),
                ("reg_date", models.DateField(default="")),
            ],
            options={
                "db_table": "review",
            },
        ),
        migrations.RenameField(
            model_name="movieinfo",
            old_name="genre",
            new_name="genre_id",
        ),
        migrations.RenameField(
            model_name="movieinfo",
            old_name="surver_id",
            new_name="tmdb_id",
        ),
        migrations.AddField(
            model_name="movieinfo",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="review_like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateField(default="")),
                ("status", models.IntegerField(default=0)),
                (
                    "review_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobbie.review",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobbie.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "review_like",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="movie_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mobbie.movieinfo",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mobbie.userinfo"
            ),
        ),
        migrations.CreateModel(
            name="movie_like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateField(default="")),
                ("status", models.IntegerField(default=0)),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobbie.movieinfo",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mobbie.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "movie_like",
            },
        ),
        migrations.CreateModel(
            name="history",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("reg_date", models.DateField(default="")),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mobbie.review"
                    ),
                ),
            ],
            options={
                "db_table": "history",
            },
        ),
    ]
